general:
  seed: &seed 4000
  run_test: True

data_gen:
  #
  # Hyperparameters passed to the DataGenerator object
  #
  gen_type: DataGenerator
  seed: *seed
  #hdf5_path: /work3/theb/boston_scalp_new.hdf5
  hdf5_path: data/hdf5/temple_seiz_sub.hdf5
  protocol: train
  window_length: &win_len 2
  stride: &stride [2,1]
  signal_name: [EEG, TCP]
  bckg_rate: &bckg_rate 20
  seiz_classes: ['cpsz', 'gnsz', 'spsz', 'tcsz', 'seiz']
  anno_based_seg: False
  prefetch_data_dir: False
  prefetch_data_from_seg: False
  train_percent: 0.9

generator_kwargs:
  seed: *seed
  batch_size: 512
  val_batch_size: 512


model_kwargs:
  #
  # Hyperparameters passed to the Model.build and __init__ methods
  #
  model_summary: True
  model: &model BaselineCNN
  dropoutprob: 0.2
  padding: False


fit:
  #
  # Hyperparameters passed to the Trainer object
  #
  # Loss function
  loss: CrossEntropy 
  weight: *bckg_rate


  # Optimization
  optimizer:
    optimizer: Adam
    lr: 0.0005 
    scheduler: None

  n_epochs: 10