general:
  seed: &seed 20
  run_test: True
  #hdf5_path: /work3/theb/boston_scalp_new.hdf5
  #hdf5_path: data/hdf5/temple_seiz_sub.hdf5

data_gen:
  #
  # Hyperparameters passed to the DataGenerator object
  #
  gen_type: DataGenerator
  seed: *seed
  protocol: all
  signal_name: [EEG, TCP]
  seiz_classes: ['fnsz','gnsz', 'cpsz', 'spsz', 'tcsz', 'seiz', 'absz', 'tnsz', 'mysz']
  excl_seiz_classes: []
  train_percent: 0.70
  val_percent: 0.15

generator_kwargs:
  seed: *seed
  batch_size: 512
  val_batch_size: 512

model_kwargs:
  #
  # Hyperparameters passed to the Model.build and __init__ methods
  #
  model_summary: True

fit:
  #
  # Hyperparameters passed to the Trainer object
  #
  # Loss function
  loss: CrossEntropy 

  # Optimization
  optimizer:
    optimizer: RMSprop
    scheduler: MultistepLR
    milestones: [50,120,150]
