name: semi_active_seiz
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.7.7
  - pip:
    - h5py==2.10.0
    - joblib==1.1.0
    - matplotlib==3.5.1
    - mne==0.24.1
    - numpy==1.20.3
    - optuna==2.10.0
    - packaging==21.3
    - pandas==1.3.3
    - prettytable==2.5.0
    - pywavelets==1.1.1
    - pyyaml==6.0
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - sqlalchemy==1.4.29
    - tensorboard==2.7.0
    - torch==1.9.1
    - git+https://esbenve:rB83GQhKSPSTN6FmLaUE@bitbucket.org/uneeg/dataapi.git@master
#prefix: /Users/theabrusch/opt/miniconda3/envs/semi_active_seiz
