name: semi_active_seiz_env
dependencies:
  - python==3.7.7
  - pip==20.2.4
  - pip:
    - numpy==1.19.5
    - pandas==1.1.4
    - git+https://esbenve:rB83GQhKSPSTN6FmLaUE@bitbucket.org/uneeg/dataapi.git@v1.1.14
    - torch