name: semi_active_seiz
channels:
  - defaults
dependencies:
  - python=3.7.7
  - pip:
    - git+https://esbenve:rB83GQhKSPSTN6FmLaUE@bitbucket.org/uneeg/dataapi.git@v1.1.14
    - h5py==2.10.0
    - llvmlite==0.37.0
    - numba==0.54.0
    - numexpr==2.7.3
    - numpy==1.20.3
    - pandas==1.3.3
    - plotly==5.3.1
    - pyedflib==0.1.19
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pywavelets==1.1.1
    - scipy==1.4.1
    - six==1.16.0
    - tabulate==0.8.9
    - tenacity==8.0.1
    - torch==1.9.1
    - pyyaml
    - scikit-learn
    - PrettyTable
    - tensorboard

